

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PesWeb.Service
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class PSESEntities : DbContext
{
    public PSESEntities()
        : base("name=PSESEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tblEvaluation> tblEvaluation { get; set; }

    public virtual DbSet<tblHeaderBot> tblHeaderBot { get; set; }

    public virtual DbSet<tblHeaderJob> tblHeaderJob { get; set; }

    public virtual DbSet<tblHeaderMid> tblHeaderMid { get; set; }

    public virtual DbSet<tblHeaderTop> tblHeaderTop { get; set; }

    public virtual DbSet<tblPosition> tblPosition { get; set; }

    public virtual DbSet<tblScore> tblScore { get; set; }

    public virtual DbSet<Period> Period { get; set; }


    public virtual int CreateForm(string empID, string evaluator, Nullable<int> jobID, string projectNO)
    {

        var empIDParameter = empID != null ?
            new ObjectParameter("EmpID", empID) :
            new ObjectParameter("EmpID", typeof(string));


        var evaluatorParameter = evaluator != null ?
            new ObjectParameter("Evaluator", evaluator) :
            new ObjectParameter("Evaluator", typeof(string));


        var jobIDParameter = jobID.HasValue ?
            new ObjectParameter("JobID", jobID) :
            new ObjectParameter("JobID", typeof(int));


        var projectNOParameter = projectNO != null ?
            new ObjectParameter("ProjectNO", projectNO) :
            new ObjectParameter("ProjectNO", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateForm", empIDParameter, evaluatorParameter, jobIDParameter, projectNOParameter);
    }


    public virtual ObjectResult<Nullable<int>> getEvaID(string evaluatorNO, string employeeNO, string projectNO)
    {

        var evaluatorNOParameter = evaluatorNO != null ?
            new ObjectParameter("EvaluatorNO", evaluatorNO) :
            new ObjectParameter("EvaluatorNO", typeof(string));


        var employeeNOParameter = employeeNO != null ?
            new ObjectParameter("EmployeeNO", employeeNO) :
            new ObjectParameter("EmployeeNO", typeof(string));


        var projectNOParameter = projectNO != null ?
            new ObjectParameter("ProjectNO", projectNO) :
            new ObjectParameter("ProjectNO", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("getEvaID", evaluatorNOParameter, employeeNOParameter, projectNOParameter);
    }


    public virtual ObjectResult<Nullable<int>> GetHeader2BYHJ(Nullable<int> hJ_ID)
    {

        var hJ_IDParameter = hJ_ID.HasValue ?
            new ObjectParameter("HJ_ID", hJ_ID) :
            new ObjectParameter("HJ_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetHeader2BYHJ", hJ_IDParameter);
    }


    public virtual ObjectResult<Nullable<int>> GetHeader3ByH2ID(Nullable<int> h2_ID)
    {

        var h2_IDParameter = h2_ID.HasValue ?
            new ObjectParameter("H2_ID", h2_ID) :
            new ObjectParameter("H2_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetHeader3ByH2ID", h2_IDParameter);
    }


    public virtual ObjectResult<Nullable<int>> GetHeaderByJobID()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetHeaderByJobID");
    }


    public virtual ObjectResult<GetEvaluationRequest_Result> GetEvaluationRequest(Nullable<int> evaluator)
    {

        var evaluatorParameter = evaluator.HasValue ?
            new ObjectParameter("evaluator", evaluator) :
            new ObjectParameter("evaluator", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEvaluationRequest_Result>("GetEvaluationRequest", evaluatorParameter);
    }


    public virtual ObjectResult<SP_GetJobDetail_Result> SP_GetJobDetail()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetJobDetail_Result>("SP_GetJobDetail");
    }


    public virtual ObjectResult<SP_GetAllHeaderJob_Result> SP_GetAllHeaderJob()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllHeaderJob_Result>("SP_GetAllHeaderJob");
    }


    public virtual ObjectResult<Nullable<int>> SP_GetHeader2BYHJ(Nullable<int> hJ_ID)
    {

        var hJ_IDParameter = hJ_ID.HasValue ?
            new ObjectParameter("HJ_ID", hJ_ID) :
            new ObjectParameter("HJ_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetHeader2BYHJ", hJ_IDParameter);
    }


    public virtual ObjectResult<SP_GetAllHeaderByJobID_Result> SP_GetAllHeaderByJobID()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllHeaderByJobID_Result>("SP_GetAllHeaderByJobID");
    }


    public virtual ObjectResult<SP_HeaderTopByJob_Result> SP_HeaderTopByJob()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HeaderTopByJob_Result>("SP_HeaderTopByJob");
    }


    public virtual ObjectResult<SP_GetHeaderMidByHeaderTopAndJobID_Result> SP_GetHeaderMidByHeaderTopAndJobID(Nullable<int> h1_ID, Nullable<int> jobID)
    {

        var h1_IDParameter = h1_ID.HasValue ?
            new ObjectParameter("H1_ID", h1_ID) :
            new ObjectParameter("H1_ID", typeof(int));


        var jobIDParameter = jobID.HasValue ?
            new ObjectParameter("JobID", jobID) :
            new ObjectParameter("JobID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetHeaderMidByHeaderTopAndJobID_Result>("SP_GetHeaderMidByHeaderTopAndJobID", h1_IDParameter, jobIDParameter);
    }


    public virtual ObjectResult<SP_HeaderTopByJobID_Result> SP_HeaderTopByJobID()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HeaderTopByJobID_Result>("SP_HeaderTopByJobID");
    }


    public virtual ObjectResult<Nullable<int>> SP_CreateEvaFormAndReturnPrimary(string empID, string evaluator, Nullable<int> jobID, string projectNO)
    {

        var empIDParameter = empID != null ?
            new ObjectParameter("EmpID", empID) :
            new ObjectParameter("EmpID", typeof(string));


        var evaluatorParameter = evaluator != null ?
            new ObjectParameter("Evaluator", evaluator) :
            new ObjectParameter("Evaluator", typeof(string));


        var jobIDParameter = jobID.HasValue ?
            new ObjectParameter("JobID", jobID) :
            new ObjectParameter("JobID", typeof(int));


        var projectNOParameter = projectNO != null ?
            new ObjectParameter("ProjectNO", projectNO) :
            new ObjectParameter("ProjectNO", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CreateEvaFormAndReturnPrimary", empIDParameter, evaluatorParameter, jobIDParameter, projectNOParameter);
    }


    public virtual int SP_InsertScore(Nullable<int> evaID, Nullable<int> h3_ID)
    {

        var evaIDParameter = evaID.HasValue ?
            new ObjectParameter("EvaID", evaID) :
            new ObjectParameter("EvaID", typeof(int));


        var h3_IDParameter = h3_ID.HasValue ?
            new ObjectParameter("H3_ID", h3_ID) :
            new ObjectParameter("H3_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertScore", evaIDParameter, h3_IDParameter);
    }


    public virtual ObjectResult<SP_GetEvaHeaderByEvaID_Result> SP_GetEvaHeaderByEvaID(Nullable<int> evaID)
    {

        var evaIDParameter = evaID.HasValue ?
            new ObjectParameter("EvaID", evaID) :
            new ObjectParameter("EvaID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEvaHeaderByEvaID_Result>("SP_GetEvaHeaderByEvaID", evaIDParameter);
    }


    public virtual int SP_DeleteHeaderTop(Nullable<int> h1_ID, Nullable<int> jobID)
    {

        var h1_IDParameter = h1_ID.HasValue ?
            new ObjectParameter("H1_ID", h1_ID) :
            new ObjectParameter("H1_ID", typeof(int));


        var jobIDParameter = jobID.HasValue ?
            new ObjectParameter("JobID", jobID) :
            new ObjectParameter("JobID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteHeaderTop", h1_IDParameter, jobIDParameter);
    }


    public virtual int SP_DeleteHeaderBot(Nullable<int> h3_ID)
    {

        var h3_IDParameter = h3_ID.HasValue ?
            new ObjectParameter("H3_ID", h3_ID) :
            new ObjectParameter("H3_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteHeaderBot", h3_IDParameter);
    }


    public virtual int SP_DeleteHeaderMid(Nullable<int> h2_ID)
    {

        var h2_IDParameter = h2_ID.HasValue ?
            new ObjectParameter("H2_ID", h2_ID) :
            new ObjectParameter("H2_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DeleteHeaderMid", h2_IDParameter);
    }


    public virtual int InsertHeaderBot(string text, Nullable<int> h2_ID)
    {

        var textParameter = text != null ?
            new ObjectParameter("Text", text) :
            new ObjectParameter("Text", typeof(string));


        var h2_IDParameter = h2_ID.HasValue ?
            new ObjectParameter("H2_ID", h2_ID) :
            new ObjectParameter("H2_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertHeaderBot", textParameter, h2_IDParameter);
    }


    public virtual int InsertHeaderMid(string text, Nullable<int> h1_ID, Nullable<int> jobID, string text_Eng)
    {

        var textParameter = text != null ?
            new ObjectParameter("Text", text) :
            new ObjectParameter("Text", typeof(string));


        var h1_IDParameter = h1_ID.HasValue ?
            new ObjectParameter("H1_ID", h1_ID) :
            new ObjectParameter("H1_ID", typeof(int));


        var jobIDParameter = jobID.HasValue ?
            new ObjectParameter("JobID", jobID) :
            new ObjectParameter("JobID", typeof(int));


        var text_EngParameter = text_Eng != null ?
            new ObjectParameter("Text_Eng", text_Eng) :
            new ObjectParameter("Text_Eng", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertHeaderMid", textParameter, h1_IDParameter, jobIDParameter, text_EngParameter);
    }


    public virtual int SP_InsertHeaderJob(Nullable<int> jobID, Nullable<int> h1_ID)
    {

        var jobIDParameter = jobID.HasValue ?
            new ObjectParameter("JobID", jobID) :
            new ObjectParameter("JobID", typeof(int));


        var h1_IDParameter = h1_ID.HasValue ?
            new ObjectParameter("H1_ID", h1_ID) :
            new ObjectParameter("H1_ID", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertHeaderJob", jobIDParameter, h1_IDParameter);
    }


    public virtual ObjectResult<Nullable<int>> InsertHeaderTop(string text, string alias, string text_Eng)
    {

        var textParameter = text != null ?
            new ObjectParameter("Text", text) :
            new ObjectParameter("Text", typeof(string));


        var aliasParameter = alias != null ?
            new ObjectParameter("Alias", alias) :
            new ObjectParameter("Alias", typeof(string));


        var text_EngParameter = text_Eng != null ?
            new ObjectParameter("Text_Eng", text_Eng) :
            new ObjectParameter("Text_Eng", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("InsertHeaderTop", textParameter, aliasParameter, text_EngParameter);
    }

}

}

