
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PesWeb.Service
{

using System;
    using System.Collections.Generic;
    
public partial class tblApprove
{

    public int ID { get; set; }

    public Nullable<int> EvaID { get; set; }

    public Nullable<int> ApproverID { get; set; }

    public Nullable<int> ApproveState { get; set; }

    public string Position { get; set; }

    public Nullable<int> PositionID { get; set; }

    public Nullable<int> HR { get; set; }

    public Nullable<int> GM { get; set; }

    public Nullable<int> PM { get; set; }

    public Nullable<int> ST { get; set; }

    public string ProjectCode { get; set; }

    public string Role { get; set; }

    public string Name { get; set; }

}

}
