
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PesWeb.Service
{

using System;
    using System.Collections.Generic;
    
public partial class tblFlowMaster
{

    public int ID { get; set; }

    public string CodeName { get; set; }

    public string PositionName { get; set; }

    public Nullable<int> FromTable { get; set; }

    public Nullable<int> Flow { get; set; }

}

}
