
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PesWeb.Service
{

using System;
    using System.Collections.Generic;
    
public partial class tblHeaderAdditional
{

    public int H_ID { get; set; }

    public Nullable<int> parent { get; set; }

    public string Text { get; set; }

    public string Text_Eng { get; set; }

    public Nullable<int> Eva_ID { get; set; }

    public string Alias { get; set; }

    public Nullable<int> H_Level { get; set; }

    public Nullable<int> point { get; set; }

    public Nullable<int> Part2ID { get; set; }

    public Nullable<int> H_status { get; set; }

}

}
