
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PesWeb.Service
{

using System;
    using System.Collections.Generic;
    
public partial class tblHeaderLevel
{

    public Nullable<int> ParentID { get; set; }

    public Nullable<int> ParentLevel { get; set; }

    public Nullable<int> CurrentID { get; set; }

    public Nullable<int> CurrentLevel { get; set; }

    public Nullable<int> Different { get; set; }

    public int seq { get; set; }

}

}
