
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PesWeb.Service
{

using System;
    using System.Collections.Generic;
    
public partial class tbllHeaderPosition
{

    public Nullable<int> HeaderID { get; set; }

    public Nullable<int> PositionNO { get; set; }

    public int ID { get; set; }

}

}
