
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PesWeb.Service
{

using System;
    using System.Collections.Generic;
    
public partial class tblScore
{

    public int Score_ID { get; set; }

    public Nullable<int> H3_ID { get; set; }

    public Nullable<int> point { get; set; }

    public Nullable<int> Eva_ID { get; set; }

    public string Comment { get; set; }

}

}
