//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesWeb.Service.Security
{
    using System;
    using System.Collections.Generic;

    public partial class tbs_PermissionUserMap
    {
        public int PermissionMapId { get; set; }
        public string AcResourceName { get; set; }
        public string UserCode { get; set; }
        public string PermissionCode { get; set; }
    }
}
